include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    type_annotate_public_apis: false
    lines_longer_than_80_chars: false
    require_trailing_commas: true
    use_super_parameters: true
