name: scrollable_clean_calendar
description: A clean calendar widget with vertical scroll, locale, and range selection date
version: 2.0.3
homepage: https://github.com/FabioFiuza/scrollable_clean_calendar

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
